# Generated by Django 4.2.8 on 2023-12-22 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_img_alter_comment_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
