# Generated by Django 5.0 on 2023-12-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/img/'),
        ),
    ]
