# Generated by Django 4.2.8 on 2023-12-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_theme_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
